# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 726281b205fbf1eed7d698e39def38d02ce844e30eea23b9202821dd10aff56177fe067de1e7de0b9057da96c33fac3e65572bbc0f1ff291c6239d32d2f2662c

test:
  secret_key_base: 87a9bfa26d927c6a53fbd5449d608930218f57893477d4bc02fe9f7d00d54108dc35f45c178d50927a93b7b09a66dd74d2229037e3a63b261bc76a8a62b33591

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
